version: "3.8"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5432:5432"  # Optional: Expose to host for debugging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 2s
      timeout: 2s
      retries: 5

  test-runner:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      TEST_DB_URL: postgresql://test_user:test_pass@db:5432/test_db
    command: poetry run pytest tests
